import EntityPacket.Codec

namespace EntityPacket

/-! # The Python codec, emitted from the spec

`transport-gateway-python` and `transport-ingest-python` are a second implementation of the
WebTransport contract, on a stack that shares nothing with picoquic. A second implementation
that retyped this layout would test that two people can read the same table, which is not the
property anybody wants from it.

So the Python codec is emitted here for the same reason the C one is in `EmitC.lean`: every
offset and width comes from `Codec.lean` rather than being typed again. `packet_golden.csv` is
what turns "emitted from the spec" into a claim about bytes, and both languages are held to the
same 64 vectors.

The emitted module writes and reads a field at a time at a named offset. A single
`struct.Struct("<I3q3hIII3h42s")` would be shorter and would state the layout a second time, as
a position in a format string that no longer mentions the offset it stands for. Moving a field
in `Codec.lean` would leave that string wrong and passing.
-/

private def u : Nat → String := toString

/-- The module, as a string. Pure, so `Emit.lean` only has to write it. -/
def pyModule : String :=
  let off (n : Nat) := u n
"\"\"\"The 100-byte fabric entity packet, in Python.

GENERATED by `lake exe packet_emit` in v-sekai-multiplayer-fabric/lean-entity-packet.
Do not edit: edit EntityPacket/Codec.lean, which is where the layout is specified and where
the Plausible roundtrip properties hold it, then emit again.

The wire is fully integral -- no floats anywhere -- so position is int64 absolute micrometres
and velocity is an int16 scaled against V_MAX. That is what lets the same hundred bytes be
compared byte for byte across Lean, C, C++, GDScript and Python, which packet_golden.csv is
for.

SPDX-License-Identifier: MIT
\"\"\"

from __future__ import annotations

from dataclasses import dataclass, field

SIZE = " ++ u SIZE ++ "
PAYLOAD_OFFSET = " ++ u PAYLOAD_OFFSET ++ "
PAYLOAD_LEN = " ++ u PAYLOAD_LEN ++ "

# The i16 velocity scale, in micrometres per tick. A velocity field means nothing without the
# scale it was divided by, so it travels with the layout rather than beside it. Same number as
# PBVH_V_MAX_PHYSICAL_DEFAULT in lean-spatial-oracle's predictive_bvh.h.
V_MAX_PHYSICAL_DEFAULT_UM_PER_TICK = " ++ u V_MAX_UM_PER_TICK ++ "

# Where each field sits on the wire. Emitted from Codec.lean's own offsets.
OFF_GID = " ++ off OFF_GID ++ "
OFF_POS = " ++ off OFF_POS ++ "
OFF_VEL = " ++ off OFF_VEL ++ "
OFF_HLC = " ++ off OFF_HLC ++ "
OFF_CLASS_OWNER = " ++ off OFF_CLASS_OWNER ++ "
OFF_SUB_INDEX = " ++ off OFF_SUB_INDEX ++ "
OFF_ROT = " ++ off OFF_ROT ++ "


def _pu32(b: bytearray, off: int, v: int) -> None:
    b[off : off + 4] = (v & 0xFFFFFFFF).to_bytes(4, \"little\", signed=False)


def _gu32(b: bytes, off: int) -> int:
    return int.from_bytes(b[off : off + 4], \"little\", signed=False)


def _pi64(b: bytearray, off: int, v: int) -> None:
    b[off : off + 8] = (v & 0xFFFFFFFFFFFFFFFF).to_bytes(8, \"little\", signed=False)


def _gi64(b: bytes, off: int) -> int:
    return int.from_bytes(b[off : off + 8], \"little\", signed=True)


def _pi16(b: bytearray, off: int, v: int) -> None:
    b[off : off + 2] = (v & 0xFFFF).to_bytes(2, \"little\", signed=False)


def _gi16(b: bytes, off: int) -> int:
    return int.from_bytes(b[off : off + 2], \"little\", signed=True)


@dataclass
class Packet:
    \"\"\"An entity envelope's integral fields, position already in micrometres.\"\"\"

    gid: int = 0
    pos_um_x: int = 0
    pos_um_y: int = 0
    pos_um_z: int = 0
    vel_x: int = 0
    vel_y: int = 0
    vel_z: int = 0
    hlc: int = 0
    class_owner: int = 0  # (class << 24) | owner
    sub_index: int = 0
    rot_x: int = 0  # swing-twist
    rot_y: int = 0
    rot_z: int = 0
    payload: bytes = field(default_factory=lambda: bytes(PAYLOAD_LEN))


def encode(p: Packet) -> bytes:
    \"\"\"Every byte is written, including the unassigned gap at 36..39, so an encode never
    leaks whatever was in the caller's buffer.\"\"\"
    b = bytearray(SIZE)
    _pu32(b, OFF_GID, p.gid)
    _pi64(b, OFF_POS + 0, p.pos_um_x)
    _pi64(b, OFF_POS + 8, p.pos_um_y)
    _pi64(b, OFF_POS + 16, p.pos_um_z)
    _pi16(b, OFF_VEL + 0, p.vel_x)
    _pi16(b, OFF_VEL + 2, p.vel_y)
    _pi16(b, OFF_VEL + 4, p.vel_z)
    _pu32(b, OFF_HLC, p.hlc)
    _pu32(b, OFF_CLASS_OWNER, p.class_owner)
    _pu32(b, OFF_SUB_INDEX, p.sub_index)
    _pi16(b, OFF_ROT + 0, p.rot_x)
    _pi16(b, OFF_ROT + 2, p.rot_y)
    _pi16(b, OFF_ROT + 4, p.rot_z)
    pay = p.payload[:PAYLOAD_LEN]
    b[PAYLOAD_OFFSET : PAYLOAD_OFFSET + len(pay)] = pay
    return bytes(b)


def decode(data: bytes) -> Packet:
    if len(data) != SIZE:
        raise ValueError(f\"a packet is {SIZE} bytes, got {len(data)}\")
    return Packet(
        gid=_gu32(data, OFF_GID),
        pos_um_x=_gi64(data, OFF_POS + 0),
        pos_um_y=_gi64(data, OFF_POS + 8),
        pos_um_z=_gi64(data, OFF_POS + 16),
        vel_x=_gi16(data, OFF_VEL + 0),
        vel_y=_gi16(data, OFF_VEL + 2),
        vel_z=_gi16(data, OFF_VEL + 4),
        hlc=_gu32(data, OFF_HLC),
        class_owner=_gu32(data, OFF_CLASS_OWNER),
        sub_index=_gu32(data, OFF_SUB_INDEX),
        rot_x=_gi16(data, OFF_ROT + 0),
        rot_y=_gi16(data, OFF_ROT + 2),
        rot_z=_gi16(data, OFF_ROT + 4),
        payload=bytes(data[PAYLOAD_OFFSET : PAYLOAD_OFFSET + PAYLOAD_LEN]),
    )


def decode_slice(data: bytes) -> list[Packet]:
    \"\"\"A slice is back-to-back records with no framing and the count is len // SIZE. A
    length that is not a multiple of SIZE is malformed rather than short: trimming it would
    hand the caller entities built from another entity's bytes.\"\"\"
    if len(data) % SIZE != 0:
        raise ValueError(f\"a slice is a multiple of {SIZE} bytes, got {len(data)}\")
    return [decode(data[i : i + SIZE]) for i in range(0, len(data), SIZE)]
"

end EntityPacket
